services:
  spring-boot-serveur:
    build:
      context: .
      dockerfile: Dockerfile
    image: serveur-tp2full
    ports:
      - "9090:8080"
    networks:
      - app-network
    volumes:
      - "./data:/app/data"

  angular-app:
    build:
      context: ./Frontend/EventManagementApp/
      dockerfile: Dockerfile
    image: angular-app-tp2
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend/EventManagementApp:/app
      - /app/node_modules
    networks:
      - app-network
    command: ["npm", "start", "--", "--host", "0.0.0.0"]

volumes:
  db_data:

networks:
  app-network:
